### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by vinhnglx** [FancyBlog/blackhulk#14]
**Table of contents:**

- BlackHulk - What is this?

- How to install

- Deploy to Heroku

- Contributor

@duykhoa anything else?

**Comment by duykhoa** [comment]
Do you mean what is **it**? :smile_cat: 

Does what is this involve how it works?

Need a licence (GPL or what else...)
It's new thing I learn from this https://www.nczonline.net/blog/2015/12/why-im-not-using-your-open-source-project/

**Comment by vinhnglx** [comment]
just introduce about BlackHulk and How it works?

Okay, I don't know about the license :)...will read it

**Comment by duykhoa** [comment]
I don't either haha. Go ahead :clap:
