### ISSUE TITLE
Why only load blog_title attribute when the router is loaded (CLGT (can loi giai thich) )

### ISSUE THREAD

**Issue by duykhoa** [FancyBlog/blackhulk#16]
Check this commit message

https://github.com/FancyBlog/blackhulk/commit/d94c96c801314dcb6f668b4ab98ea5c46c32c862

For more information.

Seem like work perfectly, but only blog_title is loaded, the blog_desc always display as undefined :trollface:

**Comment by vinhnglx** [comment]
:trollface:

**Comment by duykhoa** [comment]
No idea, may be becaz **blog_description** attr has more character than?

**Comment by vinhnglx** [comment]
really :trollface:  ???

**Comment by duykhoa** [comment]
nope, jk :octocat:

**Comment by vinhnglx** [comment]
hehe.... Look like know issue, will do it after first release :dancer:

**Comment by duykhoa** [comment]
okay, sound good :+1:

**Comment by duykhoa** [comment]
it may be related to the app-router element's callback

the event is triggered before Polymer#ready callback, so the binding is broken.


Here are a few solution to fix:

- Make a different xhr request to get blog_setting from rails server

so we send 2 requests: 1 for data.json, 1 for blog_setting.

- Use native route, or different router library

1 biggest weak point of the native routes is the combination of elements wont work anymore. It means we can't combine everything to a single file with vulcanize. Each page will reload the whole library (just hope that brower's cache will help us caching some stuffs).

**Comment by duykhoa** [comment]
Close for now... @vinhnglx Please let me know if the performance still suck :smiley:
